import argparse
import sys

HEADER_TEMPLATE = """
// Copyright (c) 2018 GitHub, Inc.
// Use of this source code is governed by the MIT license that can be
// found in the LICENSE file.

// This file is generated by tools/gen-chrome-version-header.py, you should
// never modify it by hand.

#ifndef ATOM_COMMON_CHROME_VERSION_H_
#define ATOM_COMMON_CHROME_VERSION_H_

#define CHROME_VERSION_STRING "{}"
#define CHROME_VERSION "v" CHROME_VERSION_STRING

#endif  // ATOM_COMMON_CHROME_VERSION_H_
"""

def main():
  parser = argparse.ArgumentParser()
  parser.add_argument('--input-deps', required=True,
                    help='The path to the DEPS file to read the chromium_version'
                         ' from')
  parser.add_argument('--output-path', required=True,
                    help='The path to write the generated header file to ')

  args = parser.parse_args()

  chrome_version = None

  with open(args.input_deps) as f:
    lines = f.readlines()
    for i in range(len(lines)):
      if 'chromium_version' in lines[i]:
        chrome_version = lines[i + 1].split("'")[1].split("'")[0]
        break
  
  if chrome_version is None:
    raise Exception("Could not find chromium_version in provided DEPS file")

  with open(args.output_path, "w") as f:
    f.write(HEADER_TEMPLATE.format(chrome_version))


if __name__ == '__main__':
  sys.exit(main())
